[Update] 3.4.2 (#310)
* fixes #309

* fixes #306

* handles #302 with the exception of tax brackets.

* remove this line

* version bump

* fix

* rework XP and Currency formulas + few fixes

* fix bug fixes + dexterity changes

* use dpymenus in more places in adventure

* add backpack dpymenus

* ...

* kill `enable_chests` setting + add tax bracked to `economysettings`

* style

* fix a tinkerer bug

* fix a tinkerer bug properly

* fix an issue with pets

* forging rework

* *sigh*

* negatives here would be bad

* redo this part

* update make files

* fix AttributeError: 'NoneType' object has no attribute 'user'

* fix reactions not being added

* fix reactions not being added

* ffs